#!/bin/bash

# SPDX-FileCopyrightText: 2025 Arthur A. Gleckler
# SPDX-License-Identifier: MIT

usage() {
   echo "Usage: `(basename $0)` [--no-ignore] <dir1> <dir2> <sample_size>"
   exit 1
}

NO_IGNORE=""

if [ "$1" == "--no-ignore" ]; then
  NO_IGNORE="--no-ignore"
  shift
fi

if [ "$#" -ne 3 ]; then
   usage
fi

DIR1="$1"
DIR2="$2"
SAMPLE_SIZE="$3"

check_dependency() {
  msg="$1"
  shift
  if [ "$#" -eq 1 ]; then
    command -v "$1" &> /dev/null || { echo "Please install $1$msg first." >&2; exit 1; }
  else
    for cmd in "$@"; do
      if command -v "$cmd" &> /dev/null; then
        echo "$cmd"
        return 0
      fi
    done
    echo "Please install one of: $* $msg first." >&2
    exit 1
  fi
}

FD_CMD=$(check_dependency "" fdfind fd)

check_dependency " (from GNU Coreutils)" mktemp
check_dependency "" openssl
check_dependency " (from GNU Coreutils)" shuf
check_dependency "" xargs

if [ ! -d "$DIR1" ]; then
   echo "First directory does not exist: $DIR1"
   usage
fi

if [ ! -d "$DIR2" ]; then
   echo "Second directory does not exist: $DIR2"
   usage
fi

if ! [[ "$SAMPLE_SIZE" =~ ^[0-9]+$ ]]; then
   echo "Sample size must be a positive integer"
   usage
fi

TEMP_DIR=$(mktemp -d)

trap "rm -rf $TEMP_DIR" 0 1 15
$FD_CMD $NO_IGNORE --type f . "$DIR1" | shuf -n $SAMPLE_SIZE > "$TEMP_DIR/random-sample.txt"

SAMPLE_SIZE=$(wc -l < "$TEMP_DIR/random-sample.txt"|xargs)

while read -r dir1_file; do
   relative_path="${dir1_file#$DIR1/}"
   dir2_file="$DIR2/$relative_path"

   echo -n Checking $relative_path...
   if [[ -f "$dir2_file" ]]; then
     dir1_checksum=$(openssl dgst -sha256 "$dir1_file" | awk '{ print $1 }')
     dir2_checksum=$(openssl dgst -sha256 "$dir2_file" | awk '{ print $1 }')

     if [[ "$dir1_checksum" != "$dir2_checksum" ]]; then
       echo
       echo "  MISMATCH"
       ((mismatch++))
     else
       echo " identical."
     fi
   else
     echo "  MISSING."
     ((mismatch++))
   fi
done < "$TEMP_DIR/random-sample.txt"
if [ -z "$mismatch" ]; then
  echo "All $SAMPLE_SIZE files sampled were identical."
elif [ "$mismatch" -eq 1 ]; then
  echo "There was 1 mismatch in $SAMPLE_SIZE samples."
else
  echo "There were $mismatch mismatches in $SAMPLE_SIZE samples."
fi
exit $(( mismatch ? 1 : 0 ))